version: '3.9'

services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - Jwt__Secret=SECRET
      - Jwt__Audience=https://localhost:44350/
      - Jwt__Issuer=https://localhost:44350/
      - Jwt__ExpiraEmMinutos=120
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=GMDB;User=sa;Password=Your_password123;
    networks:
      - gm-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - gm-network

volumes:
  sqlserver-data:

networks:
  gm-network:
    driver: bridge
